# Generated by Django 5.0.1 on 2024-02-03 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journeys', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='journey',
            name='base_file',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
