# Generated by Django 5.0.4 on 2024-05-10 01:40

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='metadata',
            field=models.JSONField(default={}),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('system', 'system'), ('assistant', 'assistant'), ('user', 'user')], max_length=16)),
                ('content', models.TextField(max_length=1024, validators=[django.core.validators.MaxLengthValidator(1024, 'Message content cannot exceed 1024 characters.')])),
                ('quote', models.TextField(blank=True, max_length=1024, null=True, validators=[django.core.validators.MaxLengthValidator(1024, 'Quoted content cannot exceed 1024 characters.')])),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='documents.document')),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
    ]
