# Generated by Django 5.0.4 on 2024-05-10 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_document_metadata_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='metadata',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
