# Generated by Django 5.0.4 on 2024-05-10 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_alter_document_metadata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
