# Generated by Django 5.0.4 on 2024-09-28 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0006_flashcard'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flashcard',
            name='referenced_page_number',
        ),
        migrations.AddField(
            model_name='document',
            name='flashcards_created',
            field=models.BooleanField(default=False),
        ),
    ]
